#!/bin/bash

#definisco shorcut per i colori e i font
#togliere 60 ai valori superiori al 90 per impostare i colori a basso contrasto
def='\033[0m'
orange='\033[33m\033[1m'
green='\033[32m\033[1m'
cyan='\033[96m\033[1m'
red='\033[31m\033[1m'

echo -e "${def}Benvenuto nello script per la compilazione assistita dell'esame di Sistemi Operativi"
echo -e "Iniziamo subito!"
echo ""

chmod a+x .ShellComposer
bash .ShellComposer

echo -e "${def}--------------------------"

chmod a+x .CComposer
bash .CComposer
