#!/bin/bash

#definisco shorcut per i colori e i font
#togliere 60 ai valori superiori al 90 per impostare i colori a basso contrasto
def='\033[0m'
orange='\033[33m\033[1m'
green='\033[32m\033[1m'
cyan='\033[96m\033[1m'
red='\033[31m\033[1m'

val=$1
target=$2

while true
do
	echo -e "${orange}Quale versione ti serve?${def}"

	echo "1. Numero intero strettamente positivo"
	echo "2. Numero intero maggiore di un numero specificato"
	echo -e "3. Numero intero compreso in un range${cyan}"

	read V
	case $V in
		1) cat .ctrlNum.txt > /tmp/fileTemp
		   break ;;
		2) echo -e "${orange}Inserisci il numero minimo accettato (compreso)${cyan}"
		   read N
		   cat .ctrlRngNeg.txt > /tmp/fileTemp
		   sed -i s/{limite}/$N/g /tmp/fileTemp
		   break ;;
		3) echo -e "${orange}Inserisci il valore massimo del range (compreso)${cyan}"
		   read N
		   cat .ctrlRngPos.txt > /tmp/fileTemp
		   sed -i s/{limite}/$N/g /tmp/fileTemp
		   break ;;
		*) echo -e "${red}$V non numero o non disponibile" ;;
	esac
done

confermato=0

while true
do
	echo -e "${orange}Che lettera vuoi utilizzare?${cyan}"
	read L

	while true
	do
		echo -e "${orange}Hai scritto \"$L\", confermi? (Y/N)${cyan}"
		read Q

		case $Q in
			s|S|y|Y) confermato=1 
					 break ;;
			n|N) break ;;
			*) echo -e "${red}Perfavore inserisci una risposta valida" ;;
		esac
	done

	if [ $confermato -eq 1 ]
	then
		break
	fi
done

sed -i s/{lettera}/$L/g /tmp/fileTemp
sed -i s/{num}/'$'$val/g /tmp/fileTemp
cat < /tmp/fileTemp >> $target/FCP.sh

echo -n "\$$L " >> /tmp/lettersTemp

echo -e "${green}Componente \"$0 ver. $V\" inserita correttamente!" 