#!/bin/sh

val=$1
target=$2

while true
do
	echo "Quale versione ti serve?"

	echo "1. Numero intero strettamente positivo"
	echo "2. Numero compreso in un range"

	read V
	case $V in
		1) cat .ctrlNum > /tmp/fileTemp
		   break ;;
		2) echo "Inserisci il numero minimo accettato"
		   read L
		   cat .ctrlRng > /tmp/fileTemp
		   sed -i s/{limite}/$V/g /tmp/fileTemp
		   break ;;
		*) echo "$V non numero o non corretto" ;;
	esac
done

echo "Che lettera vuoi utilizzare?"
read L

sed -i s/{lettera}/$L/g /tmp/fileTemp
sed -i s/{num}/'$'$val/g /tmp/fileTemp
cat < /tmp/fileTemp >> $target/FCP.sh
echo "Componente $0 inserita correttamente"
