#!/bin/bash

val=$1
target=$2

while true
do
	echo "Quale versione ti serve?"

	echo "1. Numero intero strettamente positivo"
	echo "2. Numero intero maggiore di un numero specificato"
	echo "3. Numero intero compreso in un range"

	read V
	case $V in
		1) cat .ctrlNum > /tmp/fileTemp
		   break ;;
		2) echo "Inserisci il numero minimo accettato (compreso)"
		   read N
		   cat .ctrlRngNeg > /tmp/fileTemp
		   sed -i s/{limite}/$N/g /tmp/fileTemp
		   break ;;
		3) echo "Inserisci il valore massimo del range (compreso)"
		   read N
		   cat .ctrlRngPos > /tmp/fileTemp
		   sed -i s/{limite}/$N/g /tmp/fileTemp
		   break ;;
		*) echo "$V non numero o non corretto" ;;
	esac
done

echo "Che lettera vuoi utilizzare?"
read L

sed -i s/{lettera}/$L/g /tmp/fileTemp
sed -i s/{num}/'$'$val/g /tmp/fileTemp
cat < /tmp/fileTemp >> $target/FCP.sh

echo -n "\$$L "  >> /tmp/lettersTemp

echo "Componente $0 inserita correttamente"
